# Generated by Django 6.0.1 on 2026-01-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('fullname', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
