# Generated by Django 6.0.1 on 2026-01-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobilenumber',
            field=models.CharField(max_length=15),
        ),
    ]
